name: Build Deb

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@latest
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Theos Dependencies
        run: |
          brew install ldid fakeroot make

      - name: Install Theos
        uses: actions/checkout@latest
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Build Package
        env:
          THEOS: theos
        run: gmake package || exit 0

      - name: Upload Deb File
        uses: actions/upload-artifact@latest
        with:
          name: "Package built on macOS"
          path: ${{ github.workspace }}/packages/*.deb
